// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZaalVpn.API;

#nullable disable

namespace ZaalVpn.API.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20250318072434_InitMainData")]
    partial class InitMainData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("auth")
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZaalVpn.API.Entities.ConfigEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTimeAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("tbConfigs", "vpn");
                });

            modelBuilder.Entity("ZaalVpn.API.Entities.CountryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTimeAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbCountries", "vpn");
                });

            modelBuilder.Entity("ZaalVpn.API.Entities.GenderEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTimeAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbGenders", "auth");

                    b.HasData(
                        new
                        {
                            Id = "8322d0eabe3446e1adaa60e90bf1d9c8",
                            CreateTimeAt = new DateTime(2025, 3, 18, 10, 54, 30, 165, DateTimeKind.Local).AddTicks(3218),
                            Gender = "Male"
                        },
                        new
                        {
                            Id = "24f1c8d29ec843578f9d44c0ecfd037d",
                            CreateTimeAt = new DateTime(2025, 3, 18, 10, 54, 30, 165, DateTimeKind.Local).AddTicks(3899),
                            Gender = "Female"
                        },
                        new
                        {
                            Id = "70e096c446dd48d181854a3d42f07ef1",
                            CreateTimeAt = new DateTime(2025, 3, 18, 10, 54, 30, 165, DateTimeKind.Local).AddTicks(3982),
                            Gender = "NonBinary"
                        },
                        new
                        {
                            Id = "5ad711dfe0284848bf67256c6fe24729",
                            CreateTimeAt = new DateTime(2025, 3, 18, 10, 54, 30, 165, DateTimeKind.Local).AddTicks(4000),
                            Gender = "Bigender"
                        },
                        new
                        {
                            Id = "c297e2da90a74adbb15c2c050e715863",
                            CreateTimeAt = new DateTime(2025, 3, 18, 10, 54, 30, 165, DateTimeKind.Local).AddTicks(4014),
                            Gender = "Agender"
                        },
                        new
                        {
                            Id = "b03322517ab94376b543df4e4ba36e1f",
                            CreateTimeAt = new DateTime(2025, 3, 18, 10, 54, 30, 165, DateTimeKind.Local).AddTicks(4037),
                            Gender = "Feminine"
                        },
                        new
                        {
                            Id = "24da78b22d2f409d80285c0f6aa0000c",
                            CreateTimeAt = new DateTime(2025, 3, 18, 10, 54, 30, 165, DateTimeKind.Local).AddTicks(4051),
                            Gender = "Androgynous"
                        },
                        new
                        {
                            Id = "e37838f172f6449f880544f7ce97f60c",
                            CreateTimeAt = new DateTime(2025, 3, 18, 10, 54, 30, 165, DateTimeKind.Local).AddTicks(4063),
                            Gender = "Other"
                        });
                });

            modelBuilder.Entity("ZaalVpn.API.Entities.RoleApplication", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("tbRoles", "auth");

                    b.HasData(
                        new
                        {
                            Id = "54c9bb4b-1693-4818-8a71-fb9b9c825a8c",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = "559ecd36-deaf-4c9b-882a-598830d69103",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("ZaalVpn.API.Entities.RoleClaimApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("tbRoleClaims", "auth");
                });

            modelBuilder.Entity("ZaalVpn.API.Entities.ServerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTimeAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("tbServers", "vpn");
                });

            modelBuilder.Entity("ZaalVpn.API.Entities.UserApplication", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTimeAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("GenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("tbUsers", "auth");

                    b.HasData(
                        new
                        {
                            Id = "cb6b5c8e-e9b4-4956-8149-aba76a6552f7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d2c70f2b-6e8f-4db1-b429-af19369df6e4",
                            CreationTimeAt = new DateTime(2025, 3, 18, 10, 54, 30, 165, DateTimeKind.Local).AddTicks(5610),
                            Email = "brok@gmail.com",
                            EmailConfirmed = true,
                            GenderId = "8322d0eabe3446e1adaa60e90bf1d9c8",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEHjFU7PNJLLoHEokVux2vyJtpz8gyHfU6EnQQ46PvnsIoWEyCtsTjPqMSAyjmYeyvw==",
                            SecurityStamp = "5d00bf30-e2a2-447f-96d6-11aedfa4820f",
                            ShortId = "111111",
                            UserName = "brok"
                        });
                });

            modelBuilder.Entity("ZaalVpn.API.Entities.UserClaimApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("tbUserClaim", "auth");
                });

            modelBuilder.Entity("ZaalVpn.API.Entities.UserLoginApplication", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("tbUserLogins", "auth");
                });

            modelBuilder.Entity("ZaalVpn.API.Entities.UserRoleApplication", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("tbUserRoles", "auth");

                    b.HasData(
                        new
                        {
                            UserId = "cb6b5c8e-e9b4-4956-8149-aba76a6552f7",
                            RoleId = "54c9bb4b-1693-4818-8a71-fb9b9c825a8c"
                        },
                        new
                        {
                            UserId = "cb6b5c8e-e9b4-4956-8149-aba76a6552f7",
                            RoleId = "559ecd36-deaf-4c9b-882a-598830d69103"
                        });
                });

            modelBuilder.Entity("ZaalVpn.API.Entities.UserTokenApplication", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("tbUserTokens", "auth");
                });

            modelBuilder.Entity("ZaalVpn.API.Entities.ConfigEntity", b =>
                {
                    b.HasOne("ZaalVpn.API.Entities.ServerEntity", "Server")
                        .WithMany("Configs")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("ZaalVpn.API.Entities.RoleClaimApplication", b =>
                {
                    b.HasOne("ZaalVpn.API.Entities.RoleApplication", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ZaalVpn.API.Entities.ServerEntity", b =>
                {
                    b.HasOne("ZaalVpn.API.Entities.CountryEntity", "Country")
                        .WithMany("Servers")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ZaalVpn.API.Entities.UserApplication", b =>
                {
                    b.HasOne("ZaalVpn.API.Entities.GenderEntity", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("ZaalVpn.API.Entities.UserClaimApplication", b =>
                {
                    b.HasOne("ZaalVpn.API.Entities.UserApplication", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZaalVpn.API.Entities.UserLoginApplication", b =>
                {
                    b.HasOne("ZaalVpn.API.Entities.UserApplication", "User")
                        .WithMany("UserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZaalVpn.API.Entities.UserRoleApplication", b =>
                {
                    b.HasOne("ZaalVpn.API.Entities.RoleApplication", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZaalVpn.API.Entities.UserApplication", "User")
                        .WithMany("Role")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZaalVpn.API.Entities.UserTokenApplication", b =>
                {
                    b.HasOne("ZaalVpn.API.Entities.UserApplication", "User")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZaalVpn.API.Entities.CountryEntity", b =>
                {
                    b.Navigation("Servers");
                });

            modelBuilder.Entity("ZaalVpn.API.Entities.RoleApplication", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ZaalVpn.API.Entities.ServerEntity", b =>
                {
                    b.Navigation("Configs");
                });

            modelBuilder.Entity("ZaalVpn.API.Entities.UserApplication", b =>
                {
                    b.Navigation("Role");

                    b.Navigation("UserClaims");

                    b.Navigation("UserLogins");

                    b.Navigation("UserTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
